### ISSUE TITLE
jtframe files should know the active simulator

### ISSUE THREAD

**Issue by jotego** [jotego/jtframe#96]
In order for `jtframe files` to parse statements like

```
jtframe:
  - from: cpu
    unless: VERILATOR,IVERILOG
    get:
      - 8051/mc8051.yaml
```

It needs to know the active simulator. Currently `jtsim` does not pass that information on. Neither is there a way to pass it.
